from immune_system import *
from host import *
from  virus import *

PATTERN="[0-9]*$"
FASTA='fasta'

T_SIMULATION_TIME=100
D_IMMUNE_SYSTEM_DELAY=5
L_LIVER_SIZE=5000
CDR_INFECTED_CELL_DEATH_RATE=0.1
CIR_PROBABILITY_TO_INFECT_LIVER_CELL=0.1
BCR_B_CELL_RATE=5E-4
DEFAULT_REGION_LENGTH=60

###########
MUTATION_RATE=1E-5
###########

DEFAULT_MIN_SIZE=100